name: flutter_pda
description: Flutter PDA plugin.
version: 0.0.1
homepage: https://github.com/jldatas/flutter_pda.git

flutter:
  plugin:
    platforms:
      android:
        package: com.jingling.flutter_pda
        pluginClass: FlutterPdaPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  async: ^2.0.8
  test: ^1.3.0
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
